version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 /fraud-detection-ml/main.py
    ports:
      - 5001:5001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      # cache directories on the container only
      - /app/node_modules
      - /app/tmp
      # mount the rest of the source directory to container
      - .:/fraud-detection-ml
  training:
    build:
      context: .
      dockerfile: Dockerfile
